baseURL = 'https://madcap.cc/'
defaultContentLanguage = 'fr'
enableEmoji = true
languageCode = 'fr-FR'
sectionPagesMenu = 'main'
title = 'MadCap'

[markup.goldmark.parser.attribute]
block = true
title = true
[markup.goldmark.renderer]
unsafe = true

[params]
homepage = '/accueil'

[languages]
[languages.fr]
languageCode = 'fr-FR'
languageName = 'Français'
weight = 1
[[languages.fr.menus.main]]
name = 'Accueil'
pageRef = '/'
[[languages.fr.menus.main]]
name = 'Organisateurs'
pageRef = '/orga/'
[languages.fr.params]
footer = "a"

[languages.en]
languageCode = 'en-GB'
languageName = 'English'
[languages.en.menus]
[[languages.en.menus.main]]
name = 'Home'
pageRef = '/'
[[languages.en.menus.main]]
name = 'Organisers'
pageRef = '/orga/'
