baseURL = 'https://madcap.cc/'
defaultContentLanguage = 'fr'
enableEmoji = true
languageCode = 'fr-FR'
sectionPagesMenu = 'main'
title = 'MadCap'
enableRobotsTXT = true
disableKinds = ["taxonomy", "term", "rss"]

[markup.goldmark.parser.attribute]
block = true
title = true
[markup.goldmark.renderer]
unsafe = true

[params]
homepage = '/accueil'

[languages]
[languages.fr]
languageCode = 'fr-FR'
languageName = 'Français'
weight = 1
[[languages.fr.menus.main]]
name = 'Accueil'
pageRef = '/'
order = 1
[[languages.fr.menus.main]]
name = 'Organisateurs'
pageRef = '/orga/'
order = 2
[[languages.fr.menus.main]]
name = 'Contact'
pageRef = '/contact/'
order = 3
[[languages.fr.menus.main]]
name = 'Participant'
pageRef = '/participant/'
order = 4

[languages.en]
languageCode = 'en-GB'
languageName = 'English'
[languages.en.menus]
[[languages.en.menus.main]]
name = 'Home'
pageRef = '/'
order = 1
[[languages.en.menus.main]]
name = 'Organisers'
pageRef = '/orga/'
order = 2
[[languages.en.menus.main]]
name = 'Contact'
pageRef = '/contact/'
order = 3
[[languages.en.menus.main]]
name = 'Participant'
pageRef = '/participant/'
order = 4
